name: final_flutter
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.6
  permission_handler: ^5.0.0+hotfix.9
  firebase_core: ^0.4.5
  firebase_database: ^3.1.6
  provider: ^4.1.2
  flutter_spinkit: ^4.0.0
  get_it: ^4.0.2
  shared_preferences: ^0.4.3
  flutter_speed_dial: ^1.2.5
  firebase_auth: ^0.16.1


  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true
